apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 4001

---
apiVersion: v1
kind: Service
metadata:
  name: green
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 4001
