apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: backend-rollout
spec:
  strategy:
    blueGreen:
      activeService: active
      previewService: green
      autoPromotionEnabled: true
  replicas: 1 # kustomize
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnspecified: DoNotSchedule
        labelSelector:
          app: backend
    spec:
      containers:
      - name: main
        image: image #kustomize
        ports:
        - containerPort: 4001
        envFrom:
        - configMapRef:
            name: cm #kustomize
        - 
        # Other environment variables as needed
    
          
      volumes:
      - name: mongo-credentials
        secret:
          secretName: mongo-credentials